#Question no. 2

#a) Write a program to implement dictionary

In [ ]:
#printing dictionary items
my_dict = {'name': 'Priyanka', 'rollno': 41, 'age': 20, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'Hyderabad'}


my_dict['address'] = 'Hyderabad'

print(my_dict)

{'name': 'Priyanka', 'rollno': 41, 'age': 20, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'Hyderabad'}


In [ ]:
#Returns a dictionary with the specified keys and value using fromkeys()

x = ('rollno', 'year')
y = 0
my_dict = dict.fromkeys(x, y)
print(my_dict)

{'rollno': 0, 'year': 0}


In [ ]:
#Returns the value of the specified key using get()

my_dict = {'name': 'Priyanka', 'rollno': 41, 'age': 20, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'Hyderabad'}
x = my_dict.get("age")

print(x) 

20


In [ ]:
#Updates the dictionary with the specified key-value pairs

my_dict = {'name': 'Priyanka', 'rollno': 41, 'age': 20, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'Hyderabad'}

my_dict.update({'address': 'mehdipatnam'})

print(my_dict) 

{'name': 'Priyanka', 'rollno': 41, 'age': 20, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'mehdipatnam'}


In [ ]:
#popping out an item from the dictionary
my_dict = {'name': 'Priyanka', 'rollno': 41, 'age': 20, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'Hyderabad'}

my_dict.pop('age')

print(my_dict) 

{'name': 'Priyanka', 'rollno': 41, 'college': 'VJIT', 'year': 2, 'branch': 'AIE', 'address': 'Hyderabad'}


#b)write a program for calculating matrices using numpy

1) inv, 2)pinv

In [ ]:

import numpy as np
from numpy import linalg
matrix = np.array([
                [10,20,30,40],
                [34,54,36,90],
                [48,83,94,23],
                [23,45,36,89]
])

print("Inverse of matrix:\n")
print(linalg.inv(matrix))
print("\n\n")
print("Pseudo Inverse of matrix:\n")
print(linalg.pinv(matrix))

Inverse of matrix:

[[ 1.33295973e-01  1.79088944e-01 -2.08950444e-02 -2.35609639e-01]
 [-1.65086863e-01 -1.08618205e-01  2.64190217e-02  1.77207589e-01]
 [ 7.29245056e-02  2.60187335e-03 -8.00576415e-05 -3.53854775e-02]
 [ 1.95260588e-02  7.58546153e-03 -7.92570651e-03 -3.16227684e-03]]



Pseudo Inverse of matrix:

[[ 1.33295973e-01  1.79088944e-01 -2.08950444e-02 -2.35609639e-01]
 [-1.65086863e-01 -1.08618205e-01  2.64190217e-02  1.77207589e-01]
 [ 7.29245056e-02  2.60187335e-03 -8.00576415e-05 -3.53854775e-02]
 [ 1.95260588e-02  7.58546153e-03 -7.92570651e-03 -3.16227684e-03]]


3)matrix rank

In [ ]:
from numpy import linalg

matrix = np.ones(7)
print(matrix)

print("Rank of matrix: ",linalg.matrix_rank(matrix))

[1. 1. 1. 1. 1. 1. 1.]
Rank of matrix:  1


4) LSTSQ

In [ ]:
coeff_matrix = np.array([
                         [6, -9],
                         [4, 5]
])

const_matrix = np.array([1, -6])

linalg.lstsq(coeff_matrix, const_matrix)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


(array([-0.74242424, -0.60606061]),
 array([], dtype=float64),
 2,
 array([11.06420294,  5.96518343]))

5) SVD

In [ ]:
coeff_matrix = np.array([
                         [52, -8],
                         [42, 25]
])

const_matrix = np.array([1, -6])

solution = linalg.solve(coeff_matrix, const_matrix)

print(solution)

[-0.01405868 -0.21638142]


6)transpose

In [ ]:
matrix = np.random.randint(1,100,24).reshape(3,8)

print("Matrix:")
print(matrix)
print("\n\n")

print("Transpose of Matrix:")
print(matrix.transpose()) 

Matrix:
[[32 80 85 41 73 27 83 61]
 [28 98 29  1 78 99 35 11]
 [98 99 54 42 39 37 59 52]]



Transpose of Matrix:
[[32 28 98]
 [80 98 99]
 [85 29 54]
 [41  1 42]
 [73 78 39]
 [27 99 37]
 [83 35 59]
 [61 11 52]]


7) eigen values

In [ ]:
matrix = np.array([
                   [23,0,0,0],
                   [0,90,0,0],
                   [0,0,87,0],
                   [0,0,0,76]
])

print("Matrix: ")
print(matrix)

evl, evc = linalg.eig(matrix)

print("\nEigen values:")
print(evl)

print("\nEigen vectors:")
print(evc)

Matrix: 
[[23  0  0  0]
 [ 0 90  0  0]
 [ 0  0 87  0]
 [ 0  0  0 76]]

Eigen values:
[23. 90. 87. 76.]

Eigen vectors:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


8) Sort

In [ ]:
matrix = np.random.randint(1,30,24).reshape(6,4)
print(matrix)

print("\n\nsorted:")
print(np.sort(matrix, axis=None))

print("\n\nsorted row wise:")
print(np.sort(matrix, axis=0))

print("\n\nsorted column wise:")
print(np.sort(matrix, axis=1))

[[13 11 16 23]
 [ 1  1 22  6]
 [12  3 13  3]
 [29 17 27 18]
 [28 29  4 12]
 [19 26 10 12]]


sorted:
[ 1  1  3  3  4  6 10 11 12 12 12 13 13 16 17 18 19 22 23 26 27 28 29 29]


sorted row wise:
[[ 1  1  4  3]
 [12  3 10  6]
 [13 11 13 12]
 [19 17 16 12]
 [28 26 22 18]
 [29 29 27 23]]


sorted column wise:
[[11 13 16 23]
 [ 1  1  6 22]
 [ 3  3 12 13]
 [17 18 27 29]
 [ 4 12 28 29]
 [10 12 19 26]]


9) Line Space

In [ ]:
a = np.linspace(0,100,num=10)
print(a)
a = np.mgrid[1:10,5:20]
print(a)
a = np.linspace(1, 5, 5)
b = np.linspace(1,8,8)

x,y = np.meshgrid(a,b)

print(x)
print(y)
a = np.ogrid[1:10,5:20]
print(a)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
  [ 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2]
  [ 3  3  3  3  3  3  3  3  3  3  3  3  3  3  3]
  [ 4  4  4  4  4  4  4  4  4  4  4  4  4  4  4]
  [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5]
  [ 6  6  6  6  6  6  6  6  6  6  6  6  6  6  6]
  [ 7  7  7  7  7  7  7  7  7  7  7  7  7  7  7]
  [ 8  8  8  8  8  8  8  8  8  8  8  8  8  8  8]
  [ 9  9  9  9  9  9  9  9  9  9  9  9  9  9  9]]

 [[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 5  6  7  8  9 10 11 12 13 14